on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./deployment"
          remoteDir: ${{ secrets.FTP_REMOTE_DIR }}
          options: "--delete --ascii"